### PR TITLE
Create rational-emacs module for initialization.

### LINKED ISSUE #62: Define customization group
There needs to be a `defgroup` for the `rational` customize group somewhere to link the custom variables into.

I was thinking something along the lines of the following:

    (defgroup 'rational
        "A sensible starting point for hacking your own Emacs configuration."
        :group 'emacs)

The problem is that we need some place to define this which is guaranteed to be loaded. A discussion of this common source is also discussed in #59.

### PR DESCRIPTION
**Pull request by jeastman**
Attempts to address issue #59.
Fixes #62.

The contents of early-init.el and init.el have moved to functions
in the rational-emacs.el file.

early-init.el and init.el are updated to call the appropriate
functions in this new module.

All functions are updated to reflect the module name 'rational-emacs'.

### CODE REVIEW

**Comment by jeastman** [comment]
Note this PR will conflict with other unmerged PRs due to moving the content of init.el.

- The fix suggested in #67 is included in this PR (I noticed the same issue). @abarocio80
- PR #58 appeared to be under discussion, so I did not include the proposed changes. @ajxn
- PR #14 appeared to be under discussion, so I did not include the proposed changes. @mfxarc

**Comment by jeastman** [comment]
Updated skeleton (and file header) based on comments from #67

**Comment by ajxn** [comment]
I closed #58 as I didn't had time to fix it (and it was a mess when it came to commits), so that isn't a problem any more.

**Comment by jeastman** [comment]
Closing this issue as there was too much covered in it and the discussion in #59 is not completed.

**Pull request closed without merging**
