### PR TITLE
config for rational-ide

### PR DESCRIPTION
**Pull request by HumHongeKamyaab**
little step to resolve https://github.com/SystemCrafters/rational-emacs/issues/64

### CODE REVIEW

**Comment by abarocio80** [comment]
Looks good.  But I don't think of LaTeX as part of an IDE, even when it is a useful tool.  Wouldn't that be better on another module?  Just a thought.

**Comment by jeffbowman** [comment]
Good start, I think the lisp family of languages usually have something already (although there are LSPs for Clojure and Racket it seems) ala `geiser` for scheme languages, `sly` or `slime` for common lisp, `cider` for Clojure. So, not sure we would want to run `eglot-ensure` in those cases. Maybe instead of adding it to `prog-mode`, we could loop over `eglot-server-programs` as it mentions the major modes supported.

Something along the lines of (untested, might not work):

```emacs-lisp
(defun rational-ide--eglot-add-hook (mode)
  (let ((hook-name (intern (concat (symbol-name mode) "-hook"))))
    (add-hook hook-name #'eglot-ensure)))

(mapcar #'rational-ide--eglot-add-hook eglot-server-programs)
```

**Comment by bdarcus** [comment]
> ... I don't think of LaTeX as part of an IDE, even when it is a useful tool. Wouldn't that be better on another module?

It definitely belongs in its own module; `rational-latex`.

**Comment by jeffbowman** [comment]
> It definitely belongs in its own module; rational-latex.

Maybe something more generic like `rational-writing` would be more appropriate. Such a module might include some configuration for blog writing, maybe olivetti, LaTeX, etc.

**Comment by bdarcus** [comment]
> Maybe something more generic like `rational-writing` would be more appropriate. Such a module might include some configuration for blog writing, maybe olivetti, LaTeX, etc.

True, but LaTeX is only one writing mode, and there's already an org module, which is arguably more widely used in the emacs world for writing.

:shrug: 

Perhaps they could be complementary, so one could couple LaTeX/markdown/org with such a mode.

**Comment by jeffbowman** [comment]
> True, but LaTeX is only one writing mode, and there's already an org module, which is arguably more widely used in the emacs world for writing.

Fair point. No argument from me :-)

> Perhaps they could be complementary, so one could couple LaTeX/markdown/org with such a mode.

Ah, markdown mode, I had forgotten that one. But, yes, I like this idea. 

(in the interest of not polluting the discussion for this PR, maybe these ideas should go into their own issue...)

**Pull request merged**
